title = "プレラ名"
tagline = "キャッチコピー的な"
description = "ここに**詳細**を入力"
hashtag = "タグ"
favicon = "/favicon.svg"
logo = "/favicon.svg"
copyrights = [
    "2023- SBAN-Tech"
]
theme = "violet"
start = 2025-05-03T00:00:00+09:00
limit = 2025-05-05T23:59:59+09:00
end = 2025-05-06T08:59:59+09:00
timezone = "Asia/Tokyo"
guerrilla = 15

[category]
list = [
    "イベント",
    "プレラ内イベント",
    "オリジナル曲",
    "模倣",
    "リスペクト",
    "アレンジ・リミックス",
    "カバー",
    "メドレー",
    "解読",
    "ネタ",
    "中の人ネタ",
    "その他"
]
event = "イベント"

[[category.partlist]]
name = "プレラ内イベント"
end = 2024-12-31T11:59:00+09:00
