title = "プレラ名"
tagline = "キャッチコピー的な"
description = "ここに**詳細**を入力"
hashtag = "タグ"
favicon = "/favicon.svg"
logo = "/favicon.svg"
copyrights = [
    "2023- SBAN-Tech"
]
theme = "amber"
start = 2024-08-30T00:00:00+09:00
limit = 2024-09-01T23:59:59+09:00
end = 2024-09-02T08:59:59+09:00
timezone = "Asia/Tokyo"

[category]
list = [
    "イベント",
    "オリジナル曲",
    "模倣",
    "リスペクト",
    "アレンジ・リミックス",
    "カバー",
    "メドレー",
    "解読",
    "ネタ",
    "中の人ネタ",
    "その他"
]
event = "イベント"
