title = "プレラ名"
tagline = "キャッチコピー的な"
description = "ここに詳細を入力ここに詳細を入力ここに詳細を入力ここに詳細を入力ここに詳細を入力ここに詳細を入力ここに詳細を入力ここに詳細を入力ここに詳細を入力ここに詳細を入力ここに詳細を入力ここに詳細を入力ここに詳細を入力ここに詳細を入力ここに詳細を入力ここに詳細を入力"
hashtag = "タグ"
favicon = "/favicon.svg"
logo = "https://yt3.googleusercontent.com/ytc/AGIKgqN0YAABDVGuQZQiMJKEvtXKnb3PfAG1Dxb52g=s720-c-k-c0x00ffffff-no-rj"
copyrights = [
    "2023- SBAN-Tech"
]
categories = [
    "イベント",
    "模倣",
    "ネタ模倣",
    "ネタ動画",
    "オリジナル曲",
    "アレンジ・カバー",
    "OKDさん",
    "その他"
]
theme = "teal"
start = 2024-05-02T00:00:00+09:00
limit = 2024-05-09T00:00:00+09:00
end = 2024-05-10T00:00:00+09:00